meta_product_name: "Zapit.fr"
meta_title: "Zapit.fr - zapitfr"
meta_description: "Suivez facilement vos paiements récurrents et comparez-les aux autres membres de la communauté Zapit!"
meta_image: "zapit_1200x630.png" # should exist in `app/assets/images/`
twitter_account: "@zapitfr_twitter_account"   # required for Twitter Cards
